### ISSUE TITLE
getAllMigrationFiles() returns an empty array on Windows all the time

### ISSUE THREAD

**Issue by drietz** [fakhrullah/parse-dbtool#1]
Unfortunately Windows is obviously having struggles with mixed path separators, so calling .sync(...) does return an empty array all the time, so no migration is being run. 

``
function getAllMigrationFiles() {
  return FastGlob.sync(`${path.resolve(process.cwd(), migrationDirectory)}/**`);
}
``
=> `[]`

Using the "cwd" option instead seems to fix the issue.

``
function getAllMigrationFiles() {
  return FastGlob.sync(`${migrationDirectory}/**`, { cwd: process.cwd() });
}
``
=> `[ './databases/migrations/20220630102017-yourmigration.js' ]`

Can you confirm, that this change would work as expected and does not break other platforms? 
In case yes, would you mind changing it "officially"? :-)

Thank you. (Also for this small little helper for Parse Server, of couse. ;-))

**Comment by drietz** [comment]
Just saw, that relative paths are not enough for the next steps, as full absolute paths are required. So maybe the change must be like this one (first, let fast-glob find all files correctly, make absolute paths afterwards from the result):

``
function getAllMigrationFiles() {
  return FastGlob.sync(`${migrationDirectory}/**`, { cwd: process.cwd() }).map(itemPath => path.resolve(process.cwd(), itemPath));
}
``

**Comment by fakhrullah** [comment]
Hi @drietz thanks for the really helpful comment.

I updated the code in the PR #2 

Tested on Ubuntu. It is working fine.
I will take me a while to test on Windows.

Could you pull the PR and test on Windows & confirm if it is working correctly.

**Comment by drietz** [comment]
Tested the changed code of PR #2 on Windows and it worked fine.

BTW: I tried the other solution idea mentioned in the PR comments and it worked as well. 

> ```js
> const pathWildcard = path.resolve(process.cwd(), `${migrationDirectory}/**`).replace(/\\/g, '/');
> return FastGlob.sync(pathWildcard);
> ```
